export const venues = [
  {
    id: 1,
    title: "Karni Stadium Complex",
    location: "Shri Karni Nagar, Bikaner",
    distance: "~4.2 Kms",
    rating: "4.5",
    reviews: "87",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=500&auto=format&fit=crop",
    sports: ["Cricket", "Football", "Athletics", "Basketball"]
  },
  {
    id: 2,
    title: "Mahatma Gandhi Stadium",
    location: "Lalgarh Palace Road, Bikaner",
    distance: "~2.8 Kms",
    rating: "4.3",
    reviews: "65",
    image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=500&auto=format&fit=crop",
    sports: ["Swimming", "Badminton", "Tennis", "Volleyball"],
    amenities: ["Drinking water", "Changing Room", "Parking", "Equpiment rental", "First aid kit"]
  },
  {
    id: 3,
    title: "Bikaner Club Sports Arena",
    location: "Civil Lines, Bikaner",
    distance: "~1.5 Kms",
    rating: "4.7",
    reviews: "124",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop",
    sports: ["Gym", "Squash", "Table Tennis", "Yoga"]
  },
  {
    id: 4,
    title: "Pawanpuri Sports Center",
    location: "Pawanpuri Colony, Bikaner",
    distance: "~3.7 Kms",
    rating: "4.2",
    reviews: "42",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=500&auto=format&fit=crop",
    sports: ["Badminton", "Cricket Nets", "Boxing", "Gym"]
  },
  {
    id: 5,
    title: "JNV Colony Gym & Fitness",
    location: "JNV Colony, Bikaner",
    distance: "~5.1 Kms",
    rating: "4.8",
    reviews: "96",
    image: "https://images.unsplash.com/photo-1534367507877-0edd93bd013b?w=500&auto=format&fit=crop",
    sports: ["Gym", "Cardio", "Weight Training", "Personal Training"]
  },
  {
    id: 6,
    title: "Rani Bazar Indoor Arena",
    location: "Rani Bazar, Bikaner",
    distance: "~0.8 Kms",
    rating: "4.4",
    reviews: "58",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop",
    sports: ["Badminton", "Table Tennis", "Carrom", "Chess"]
  },
  {
    id: 7,
    title: "Beechwal Sports Ground",
    location: "Beechwal Industrial Area, Bikaner",
    distance: "~6.3 Kms",
    rating: "4.0",
    reviews: "33",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&auto=format&fit=crop",
    sports: ["Football", "Cricket", "Volleyball", "Kabaddi"]
  },
  {
    id: 8,
    title: "Sadul Ganj Fitness Hub",
    location: "Sadul Ganj, Bikaner",
    distance: "~4.9 Kms",
    rating: "4.6",
    reviews: "71",
    image: "https://images.unsplash.com/photo-1549060279-7e168fce7090?w=500&auto=format&fit=crop",
    sports: ["Yoga", "Meditation", "Zumba", "Aerobics"]
  }
];

export const games = [
  {
    id: 1,
    type: "Regular",
    organizer: "Sunil Marudhar",
    karma: 108,
    date: "Tue, 30 Dec 2025, 04:00 PM - 06:00 PM",
    location: "Karni Stadium - Badminton Court",
    distance: "~4.2km",
    playersGoing: 1,
    totalPlayers: 4,
    status: "Booked",
    icon: "🏸",
    level: "Beginner - Professional",
    sport: "Badminton"
  },
  {
    id: 2,
    type: "Competitive",
    organizer: "Vikram Singh",
    karma: 250,
    date: "Wed, 31 Dec 2025, 07:00 PM - 09:00 PM",
    location: "Beechwal Sports Ground",
    distance: "~6.3km",
    playersGoing: 8,
    totalPlayers: 10,
    status: "Booked",
    icon: "⚽",
    level: "Intermediate",
    sport: "Football",
    description: "🏸 BK Badminton Coaching 🏸 (Trial Class Available) ✅ Coaching for Adults & Kids – Beginners to Professional Level.",
    contact: "8587018148"
  },
  {
    id: 3,
    type: "Casual",
    organizer: "Abhishek Gaur",
    karma: 85,
    date: "Thu, 01 Jan 2026, 06:00 AM - 08:00 AM",
    location: "JNV Colony Gym",
    distance: "~5.1km",
    playersGoing: 3,
    totalPlayers: 6,
    status: "Open",
    icon: "💪",
    level: "All Levels",
    sport: "Gym Session"
  },
  {
    id: 4,
    type: "Tournament",
    organizer: "Coach Ratan",
    karma: 420,
    date: "Fri, 02 Jan 2026, 05:00 PM - 08:00 PM",
    location: "Mahatma Gandhi Stadium",
    distance: "~2.8km",
    playersGoing: 12,
    totalPlayers: 16,
    status: "Booked",
    icon: "🏀",
    level: "Advanced",
    sport: "Basketball"
  },
  {
    id: 5,
    type: "Friendly",
    organizer: "Sandeep S.",
    karma: 150,
    date: "Sat, 03 Jan 2026, 03:00 PM - 06:00 PM",
    location: "Karni Stadium Cricket Nets",
    distance: "~4.2km",
    playersGoing: 6,
    totalPlayers: 8,
    status: "Open",
    icon: "🏏",
    level: "Beginner",
    sport: "Cricket Practice"
  },
  {
    id: 6,
    type: "Regular",
    organizer: "Dr. Rajani",
    karma: 95,
    date: "Sun, 04 Jan 2026, 07:00 AM - 08:00 AM",
    location: "Sadul Ganj Fitness Hub",
    distance: "~4.9km",
    playersGoing: 8,
    totalPlayers: 15,
    status: "Booked",
    icon: "🧘",
    level: "All Levels",
    sport: "Morning Yoga"
  },
  {
    id: 7,
    type: "Competitive",
    organizer: "Rahul Purohit",
    karma: 180,
    date: "Mon, 05 Jan 2026, 06:00 PM - 08:00 PM",
    location: "Bikaner Club Tennis Court",
    distance: "~1.5km",
    playersGoing: 2,
    totalPlayers: 4,
    status: "Open",
    icon: "🎾",
    level: "Intermediate",
    sport: "Tennis"
  },
  {
    id: 8,
    type: "Regular",
    organizer: "Meera Vyas",
    karma: 120,
    date: "Tue, 06 Jan 2026, 09:00 AM - 10:00 AM",
    location: "Mahatma Gandhi Swimming Pool",
    distance: "~2.8km",
    playersGoing: 4,
    totalPlayers: 6,
    status: "Booked",
    icon: "🏊",
    level: "Beginner",
    sport: "Swimming Lesson"
  },
  {
    id: 9,
    type: "Casual",
    organizer: "Priya Sharma",
    karma: 75,
    date: "Wed, 07 Jan 2026, 07:00 PM - 08:00 PM",
    location: "Pawanpuri Sports Center",
    distance: "~3.7km",
    playersGoing: 10,
    totalPlayers: 20,
    status: "Open",
    icon: "🕺",
    level: "All Levels",
    sport: "Zumba Class"
  },
  {
    id: 10,
    type: "Friendly",
    organizer: "Arjun Singh Rathore",
    karma: 160,
    date: "Thu, 08 Jan 2026, 05:00 PM - 07:00 PM",
    location: "JNV Colony Powerlifting Area",
    distance: "~5.1km",
    playersGoing: 3,
    totalPlayers: 5,
    status: "Booked",
    icon: "🏋️",
    level: "Advanced",
    sport: "Powerlifting Session"
  }
];